### ISSUE TITLE
ImportError involving libftdi in Python2 mode

### ISSUE THREAD

**Issue by refola** [refola/python-ft232h-spi#1]
## Context

`./do.sh deps-suse` and  `./do.sh py2 install` have been successfully ran.
## Action

`./do.sh py2 run`
## Expectation

Error explaining that the device isn't plugged in
## Result

```
Running example.py....
Traceback (most recent call last):
  File "/home/mark/code/python-ft232h-spi/data/example.py", line 6, in <module>
    import Adafruit_GPIO.FT232H as FT232H
  File "build/bdist.linux-x86_64/egg/Adafruit_GPIO/FT232H.py", line 30, in <module>
  File "/usr/lib64/python2.7/site-packages/ftdi1.py", line 32, in <module>
    _ftdi1 = swig_import_helper()
  File "/usr/lib64/python2.7/site-packages/ftdi1.py", line 28, in swig_import_helper
    _mod = imp.load_module('_ftdi1', fp, pathname, description)
ImportError: dynamic module does not define init function (init_ftdi1)
```
## Further information

Searching for "dynamic module does not define init function", I found [this page](http://pitfalls-survival.blogspot.com/2009/07/importerror-dynamic-module-does-not.html) where a commenter recommends running `nm libname.so  | grep initlibname` and finding that the right init function exists but isn't exported. I ran `nm _ftdi1.so | grep init` saw that there's a `ftdi_init`, as if the ftdi library got it backwards.

**Comment by n8willis** [comment]
Hi; I just ran into this exact problem myself. It is as simple are merely renaming the function?

**Comment by refola** [comment]
I stopped developing this script months ago and no longer care to fix what's broken, especially in upstream code. I may have started this "python-ft232h-spi" install script project, but now I just want to get out of the way and let what happens happen. Feel free to poke around, ask developers of upstream projects for help, fork/copy this script, and make whatever changes you want. I'll even point people at your work if you make something better, but my development in this project is over.
